/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://2xaatgqntfcanjex5dp3qf4uta.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-k7fwzkhknnblxkqc7buwwh33sy",
    "aws_cognito_identity_pool_id": "eu-west-2:6f762efb-ffdd-4f48-8799-15c371e50191",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_911lnhqGn",
    "aws_user_pools_web_client_id": "7nlr5fa1llubi5me6du558ed86",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
